# .streamlit/secrets.toml
SUPABASE_URL = "https://fnifimhkezhhhlpvglei.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaWZpbWhrZXpoaGhscHZnbGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjY2MTIsImV4cCI6MjA3NTc0MjYxMn0.HiScRwhJr-q02RwMGGOywxIPmQOE7-ELldLRzQVg2kE"
